from __future__ import annotations

from typing import Any, Protocol


class RepositoryUnavailableError(RuntimeError):
    pass


class ProcessingResultRepository(Protocol):
    def ping(self) -> bool: ...
    def find_compatible_success(self, publication_id: int, grobid_version: str,
                                algorithm_version: str, parameters: dict[str, Any]) -> dict[str, Any] | None: ...
    def find_compatible_success_statuses(
        self, publication_ids: list[int], grobid_version: str,
        algorithm_version: str, parameters: dict[str, Any],
    ) -> dict[str, dict[str, Any]]: ...
    def save_success(self, article: Any, result: dict[str, Any], grobid_version: str,
                     algorithm_version: str, parameters: dict[str, Any]) -> int: ...
    def save_failure(self, article: Any, grobid_version: str, algorithm_version: str,
                     parameters: dict[str, Any], duration_ms: int, error_code: str,
                     error_message: str) -> int | None: ...
    def list_articles(self) -> list[dict[str, Any]]: ...
    def list_runs(self, publication_id: int) -> list[dict[str, Any]]: ...
    def get_run(self, run_id: int) -> dict[str, Any] | None: ...
    def get_comparison(self, run_id: int) -> dict[str, Any] | None: ...


class GroundTruthRepository(Protocol):
    def list_annotations(self, publication_id: int) -> list[dict[str, Any]]: ...
    def create_annotation(self, publication_id: int, data: dict[str, Any]) -> dict[str, Any]: ...
    def update_annotation(self, annotation_id: int, data: dict[str, Any]) -> dict[str, Any] | None: ...


class ExperimentRepository(Protocol):
    def create_experiment(self, data: dict[str, Any]) -> dict[str, Any]: ...
    def list_experiments(self) -> list[dict[str, Any]]: ...
    def get_experiment(self, experiment_id: int) -> dict[str, Any] | None: ...
    def add_metric(self, experiment_id: int, data: dict[str, Any]) -> dict[str, Any]: ...
