FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt requirements-debug.txt ./

RUN pip install --no-cache-dir -r requirements-debug.txt

COPY app.py .
COPY trdizin_app ./trdizin_app
COPY templates ./templates

CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
