FROM python:3.12-slim

WORKDIR /app

COPY database/importer/requirements.txt \
     /tmp/importer-requirements.txt

COPY processor/requirements.txt \
     /tmp/processor-requirements.txt

RUN pip install --no-cache-dir \
    -r /tmp/importer-requirements.txt \
    -r /tmp/processor-requirements.txt

COPY worker/run_api_pipeline.py /app/

COPY processor/process_pdfs.py /app/
COPY processor/process_remote_pdfs.py /app/

COPY database/importer/sync_trdizin_api.py /app/
COPY database/importer/import_trdizin_references.py /app/
COPY database/importer/import_grobid.py /app/
COPY database/importer/match_exact_doi.py /app/
COPY database/importer/match_references.py /app/

CMD ["python", "run_api_pipeline.py"]
